# Generated by Django 3.2.7 on 2021-09-02 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_auto_20210902_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='hates',
        ),
        migrations.AddField(
            model_name='movie',
            name='hates',
            field=models.ManyToManyField(blank=True, related_name='user_hates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='user_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
